# Assignment 1: Numpy in Jupyter with Visual Code

In [1]:
import numpy as np

In [60]:
# 1.2. Create a 2D array of size 3x3 with all zeros
def create_zero_array():
    return np.zeros((3, 3))

In [63]:
print(create_zero_array())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 1.3. Create a 2D array of size 3x3 with random intergers between 0 and 10
import numpy.random as random
def create_random_array():
    return random.randint(0, 10, (3, 3))

In [6]:
print(create_random_array())

[[0 2 8]
 [7 1 3]
 [1 2 8]]


In [7]:
# 1.4. Create an identity matrix of size 4x4
def create_identity_matrix():
    return np.eye(4)

In [9]:
print(create_identity_matrix())

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# 1.5. Multiply a 2x3 matrix with a 3x2 matrix
def multiply_matrices(A: np.ndarray, B: np.ndarray):
    return np.dot(A, B)   

# Example matrices
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[7, 8], [9, 10], [11, 12]])

print("Array A:")
print(matrix_A)
print("Array B:")
print(matrix_B)
result = multiply_matrices(matrix_A, matrix_B)
print("Result of A @ B:")
print(result)

Array A:
[[1 2 3]
 [4 5 6]]
Array B:
[[ 7  8]
 [ 9 10]
 [11 12]]
Result of A @ B:
[[ 58  64]
 [139 154]]


# Assignment 2: 2D Arrays

In [77]:
# 2.1. Create a 2D array from a list of lists
def list_to_array(list: list):
    return np.array(list)

# Example list of lists
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_from_list = list_to_array(list_of_lists)
print("Array from list of lists:")
print(array_from_list)
print(type(array_from_list))

Array from list of lists:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [12]:
# 2.2. Return shape of a 2D array
def array_shape(arr: np.ndarray):
    return arr.shape

# Example array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:")
print(array_shape(np_array))

Shape of the array:
(2, 3)


In [65]:
# 2.3. Access the first row of a 2D array
def first_row(arr: np.ndarray):
    return arr[0]

# Example array
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("First row of the array:")
print(first_row(np_array))

First row of the array:
[1 2 3]


In [67]:
# 2.4. Access the last column of a 2D array
def last_column(arr: np.ndarray):
    return arr[:, -1]

np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Last column of the array:")
print(last_column(np_array))

Last column of the array:
[3 6]


In [17]:
# 2.5. Add two 2D arrays element-wise
def add_arrays(arr1: np.ndarray, arr2: np.ndarray):
    return arr1 + arr2

# Example arrays
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
print("Array A:")
print(A)
print("Array B:")
print(B)
result = add_arrays(A, B)
print("Result of A + B:")
print(result)

Array A:
[[1 2 3]
 [4 5 6]]
Array B:
[[ 7  8  9]
 [10 11 12]]
Result of A + B:
[[ 8 10 12]
 [14 16 18]]


# Assignment 3

In [20]:
# 3.1. Return True if any element > 10
def check_greater_than_ten(arr: np.ndarray):
    return np.any(arr > 10) # return true if any element is greater than 10 or False otherwise

"""
Use conditional statements
def check_greater_than_ten(arr: np.ndarray):
    if np.any(arr > 10):
        return True
    else:   
        return False
"""

# Example array
np_array_A = np.array([[1, 2, 3], [4, 5, 6]])
print(check_greater_than_ten(np_array))
np_array_B = np.array([[11, 2, 3], [4, 5, 6]]) # Example with an element greater than 10
print(check_greater_than_ten(np_array_B))

False
True


In [69]:
# 3.2. Replace elements < 0 with 0
def replace_negatives(arr: np.ndarray):
    arr[arr < 0] = 0
    return arr

# Example array with negative values
np_array = np.array([[1, -2, 3], 
                     [-4, 5, -6]])
print("Original array:")
print(np_array)
print("Array after replacing negatives with zero:")
print(replace_negatives(np_array))

Original array:
[[ 1 -2  3]
 [-4  5 -6]]
Array after replacing negatives with zero:
[[1 0 3]
 [0 5 0]]


In [22]:
# 3.3. Count elements > 5
def count_greater_than_five(arr: np.ndarray):
    return np.sum(arr > 5)

# Example array
np_array = np.array([[4, 5, 6], 
                     [7, 8, 9]])
print("Number of elements greater than five:")
print(count_greater_than_five(np_array))

Number of elements greater than five:
4


In [23]:
# 3.4. Mark even numbers with 1, others with 0
def mark_even(arr: np.ndarray):
    #np.where(condition, value_if_true, value_if_false)
    return np.where(arr % 2 == 0, 1, 0)

# Example array
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Original array:")
print(np_array)
print("Array with even numbers marked with 1 and odd numbers with 0:")
print(mark_even(np_array))

Original array:
[[1 2 3]
 [4 5 6]]
Array with even numbers marked with 1 and odd numbers with 0:
[[0 1 0]
 [1 0 1]]


In [25]:
# 3.5. Conditional sum of elements > 5
def sum_if_greater_than_five(arr: np.ndarray):
    return arr[arr > 5].sum()

# Example array
np_array = np.array([[3, 4, 5], 
                     [6, 7, 8]])
print("Sum of elements greater than five:")
print(sum_if_greater_than_five(np_array))

Sum of elements greater than five:
21


# Assigment 4: Loop Example in 2D Array

In [ ]:
# 4.1. Sum each row manually using loops
def row_sums(arr: np.ndarray):
    return np.array([sum(row) for row in arr]) # shorter in python

"""
# manually using loops
def row_sums(arr: np.ndarray):
    sums = [] # return array of sums
    for row in arr:
        sums.append(sum(row)) # sum of each row
    return np.array(sums)
"""

# Example array
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Sum of each row in the array:")
print(row_sums(np_array))

Sum of each row in the array:
[ 6 15]


In [84]:
# 4.2. Find max in each row of 2D array using loops
def row_max(arr: np.ndarray):
    return np.array([max(row) for row in arr]) # shorter in python

"""
# manually using loops
def row_max(arr: np.ndarray):
    max_values = [] # return array of max values
    for row in arr:
        max_values.append(max(row)) # max of each row
    return np.array(max_values)
"""
# Example array
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Maximum value in each row of the array:")
print(row_max(np_array))

Maximum value in each row of the array:
[3 6]


In [83]:
# 4.3. Multiply each element by 2 using loops
def multiply_by_two(arr: np.ndarray) -> np.ndarray:
    return np.array([[element * 2 for element in row] for row in arr]) # shorter in python

"""
# manually using loops
def multiply_by_two(arr: np.ndarray):
    result = [] # return array of multiplied values
    for row in arr:
        new_row = [] # new row to store multiplied values
        for element in row:
            new_row.append(element * 2) # multiply each element by 2
        result.append(new_row) # add new row to result
    return np.array(result)
"""
# Example array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array after multiplying each element by two:")
print(multiply_by_two(np_array))

Array after multiplying each element by two:
[[ 2  4  6]
 [ 8 10 12]]


# Assignment 5: Data Manipulation

## 5.1: Shape and Reshaping

In [85]:
# 5.1.1. Reshape a 3x4 array into 2x6
def reshape_array(arr: np.ndarray):
    return arr.reshape(2, 6)

# Example array
np_array_3_4 = np.array([[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]])
print("Original array:")
print(np_array_3_4)
print("Reshaped array:")
print(reshape_array(np_array_3_4))

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [86]:
# 5.1.2. Flatten the array into 1D
def flatten(arr: np.ndarray):
    return arr.flatten()

# Example array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(np_array)
print("Flattened array:")
print(flatten(np_array))

Original array:
[[1 2 3]
 [4 5 6]]
Flattened array:
[1 2 3 4 5 6]


## 5.2: Array Iterating 2D Array

In [95]:
# 5.2.1. Print all elements using np.nditer
def iterate_elements(arr: np.ndarray):
    for element in np.nditer(arr):
        print(element, end=' ')

# Example array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
iterate_elements(np_array)

1 2 3 4 5 6 

In [105]:
# 5.2.2. Return a list of elements > 5 using iteration
def elements_greater_than_five(arr: np.ndarray):
    return [element.item() for element in np.nditer(arr) if element > 5]

# Example array
np_array = np.array([[3, 4, 5], 
                     [6, 7, 8]])
print("Original array:")
print(np_array)
print("List of elements greater than five:")
print(elements_greater_than_five(np_array))

Original array:
[[3 4 5]
 [6 7 8]]
List of elements greater than five:
[6, 7, 8]


In [107]:
# 5.2.3. Return sum using iteration
def sum_using_iteration(arr: np.ndarray):
    return sum(element.item() for element in np.nditer(arr))

# Example array
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Total sum of all elements in the array:")
print(sum_using_iteration(np_array))

Total sum of all elements in the array:
21


## 5.3: Splitting 2D Arrays

In [168]:
# 5.3.1. Split horizontally into two arrays
def split_horizontal(arr: np.ndarray):
    if arr.size % 2 != 0:
        raise ValueError("Array cannot be split horizontally into two equal parts.")
    elif arr.shape[1] % 2 != 0:
        arr = arr.reshape(arr.shape[1], arr.shape[0])
    result = np.hsplit(arr, 2)
    return result
          
# Example array  
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Original array:")
print(np_array)
print("Shape of the array:")
print(np_array.shape)
print("Split array horizontally:")
splits = split_horizontal(np_array)
for i, split in enumerate(splits):
    print(f"Split {i + 1}:")
    print(split)

Original array:
[[1 2 3]
 [4 5 6]]
Shape of the array:
(2, 3)
Split array horizontally:
Split 1:
[[1]
 [3]
 [5]]
Split 2:
[[2]
 [4]
 [6]]


In [188]:
# 5.3.2. Split vertically into two arrays
def split_vertical(arr: np.ndarray):
    if arr.size % 2 != 0:
        raise ValueError("Array cannot be split vertically into two equal parts.")
    elif arr.shape[0] % 2 != 0:
        arr = arr.reshape(arr.shape[1], arr.shape[0])
    result = np.vsplit(arr, 2)
    return result

# Example array
np_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
print("Original array:")
print(np_array)
print("Shape of the array:")
print(np_array.shape)
splits = split_vertical(np_array)
for i, split in enumerate(splits):
    print(f"Split {i + 1}:")
    print(split)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of the array:
(3, 4)
Split 1:
[[1 2 3]
 [4 5 6]]
Split 2:
[[ 7  8  9]
 [10 11 12]]


In [213]:
# 5.3.3. Split into four quadrants
def split_quadrants(arr: np.ndarray):
    return [last_split for split in split_vertical(arr) for last_split in split_horizontal(split)]

# Example array
np_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])
print("Original array:")
print(np_array)
print("Shape of the array:")
print(np_array.shape)

splits = split_quadrants(np_array)
for i, split in enumerate(splits):
    print(f"Split {i + 1}:")
    print(split)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape of the array:
(4, 4)
Split 1:
[[1 2]
 [5 6]]
Split 2:
[[3 4]
 [7 8]]
Split 3:
[[ 9 10]
 [13 14]]
Split 4:
[[11 12]
 [15 16]]


## 5.4: Array Slicing

In [226]:
# 5.4.1. Get middle row of the array
def middle_row(arr: np.ndarray):
    return arr[arr.shape[0] // 2]

# Example array
np_array = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])
print("Original array:")
print(np_array)
print("Middle row of the array:")
print(middle_row(np_array))

Original array:
[[1 2]
 [3 4]
 [5 6]]
Middle row of the array:
[3 4]


In [228]:
# 5.4.2. Get all corner elements (assume square)
def corner_elements(arr: np.ndarray):
    return [arr[0, 0], arr[0, -1], arr[-1, 0], arr[-1, -1]]

# Example array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(np_array)
print("Corner elements of the array:")
print(corner_elements(np_array))

Original array:
[[1 2 3]
 [4 5 6]]
Corner elements of the array:
[1, 3, 4, 6]


In [229]:
# 5.4.3. Return sub-array from index [start_row:end_row, start_col:end_col]
def sub_array(arr: np.ndarray, start_row: int, end_row: int, start_col: int, end_col: int):
    return arr[start_row:end_row, start_col:end_col]

np_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8],
                     [9, 10, 11, 12],
                     [13, 14, 15, 16]])
print("Original array:")
print(np_array)
print("Sub-array from index [1:3, 1:3]:")
print(sub_array(np_array, 1, 3, 1, 3))

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sub-array from index [1:3, 1:3]:
[[ 6  7]
 [10 11]]
